### ISSUE TITLE
Vat. gr. 1422

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#1]
1) Vat. gr. 1422: Ps 15–18: der Psalmtext (XML) wird ins HTML transformiert, was nicht sein sollte
2)  Vat. gr. 1422: Ps 11–18: <note type="parallels"> wird nicht transformiert
3) Vat. gr. 1422: Ps 2–18: @subtype im <quot> wird nicht transformiert:
4) Vat. gr. 1422: Ps 2–18: hexaplarische Varianten werden nicht transformiert: Beispiel:
xml:id="vat-gr-1422-hexaplaric-17-6
5) Vat. gr. 1422: ab Ps 18 wird <note type="attribution"> nicht vollständig transformiert:  Beispiel:
vat-gr-1422-fr-18-2
6) Vat. gr. 1422: Referenzen zu Coislin 187 werden nicht akzeptiert: Beispiel:
<ref target="#coislin-187:coislin-187-fr-18-10" type="identical">Paris. Coislin 187 (sine attributione)</ref>
7) Vat. gr. 1422: header:
a) <title> und <title type="subtitle"> in der Transformation nicht differenziert
b) <scriptDesc> nicht transformierbar
c) <normalization> nicht transformierbar

**Comment by tklampfl** [comment]
ad 1.) divisions have to be marked as "septuaginta": ```<div type="bibletext" ana="septuaginta">```. - Fixed.

**Comment by tklampfl** [comment]
ad 2.) ```note @type = parallels``` got a rule and is processed:
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/dcd19f37-72b7-4179-aa1b-9dfa2c65496b)

**Comment by tklampfl** [comment]
ad 3.) ```@subtye``` wird nun transformiert.

**Comment by tklampfl** [comment]
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/95b5827f-5cda-41f0-81f0-819308b04383)

**Comment by tklampfl** [comment]
Hexaplaric variants are now transformed and in the result document.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/dc9abd73-b6a3-4b39-9726-eaba4199e714)

**Comment by tklampfl** [comment]
Missing attribution from commentary to Ps 18 onwards: Encoding is different: ```<note xml:lang="grc">...</note>``` - ```<note><foreign ml:lang="grc">...```. - Fixed. Attribution now displayed.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/60c54c95-9ab6-46a0-852a-30ad9629dd8d)

**Comment by tklampfl** [comment]
Links for coislin 187 not available. - Fixed.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/8fc97d40-0a2d-463a-91ec-d48a500fb9e0)

**Comment by tklampfl** [comment]
Subtitle now distinguished from title by font size.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/d2802134-f54d-4c53-bb33-9a3ba2561be1)

**Comment by tklampfl** [comment]
Paragraph with normalization now present.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/d3b45efa-0a14-4ee1-8ec4-92f2d3972157)

**Comment by tklampfl** [comment]
The ```scriptDesc``` element is now considered in the transformation.
![grafik](https://github.com/acdh-oeaw/ExpPs/assets/56353369/ef9ece11-558b-453f-8238-9ca190ba9808)

**Comment by tklampfl** [comment]
Fixed test: prefix in ```ref @target``` includes now coislin-187.
