### ISSUE TITLE
Auct. D.4.1 (B1): <add place="overstrike">τοῦ</add> (zu finden in xml:id="bodl-auct-d-4-1-fr-7-2"): nicht transformierbar

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#10]
In Vat. gr. 754 die Transformation funktioniert bereits:
<add place="overstrike">ν</add> (zu finden in  xml:id="vat-gr-754-fr-17-112")

**Comment by tklampfl** [comment]
Doppelte Anführungszeichen durch große spitze Klammern ersetzt für den Fall ```add place=overstrike```
![image](https://github.com/user-attachments/assets/c7d370f4-5551-46e2-9cdc-196d03d3e830)
