### ISSUE TITLE
Auct. D.4.1 (B1): <supplied reason="om." resp="SPanteghini">·</supplied> (zu finden in xml:id="bodl-auct-d-4-1-fr-20-19"): zu transfromieren mit spitzen Klammern, nicht mit eckigen 

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#11]
In Vat. gr. 754 die Transformation funktioniert bereits: 
<supplied reason="om." resp="SPanteghini">θ</supplied> in xml:id="vat-gr-754-fr-17-97"

**Comment by tklampfl** [comment]
Wenn ```supplied``` mit ```reason = 'om.'``` dann wird eine spitze Klammer gesetzt.
![grafik](https://github.com/user-attachments/assets/4fa06d4a-5689-4928-b5bb-0fde506fb5be)
