### ISSUE TITLE
Auct. D.4.1 (B1):  <add place="below">.</add> (zu finden in xml:id="bodl-auct-d-4-1-fr-18-5"): nicht transformierbar

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#13]
In Vat. gr. 754 funktioniert die Transformation bereits:
<add place="below">:</add> in xml:id="vat-gr-754-fr-17-48"

**Comment by tklampfl** [comment]
Regel für ```add``` ohne ```type``` Attribut hat gefehlt. Ergänzt.
![grafik](https://github.com/user-attachments/assets/7b6729a9-6e07-4dde-9646-1921cfda2bd5)
