### ISSUE TITLE
S. Trin. 78: Ps 21: links zu Coislin 187 nicht wirksam

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#15]
Ausführliches Ref-Element: <ref
                        target="#coislin-187:coislin-187-fr-21-32" type="identical">Paris. Coislin
                        187</ref>

**Comment by AmjedKhaled165** [comment]
install this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by tklampfl** [comment]
Regel für Coislin 187 in der Logik zur Generierung der Links hinzugefügt.
