### ISSUE TITLE
Edition_online: Expositio 1: digitale Bezeugungssleiste: Handschrift M: Link zur Schrumpfdatei ist zu erstellen  

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#3]

**Comment by tklampfl** [comment]
M: Mosq. Synod. 194
Dateiname war falsch; korrigiert zu ```mosq_synod_194.html``` in Datei ```edition.js```.

**Comment by tklampfl** [comment]
In der Datei ```edition.js``` fehlt eine Zeile zur Verarbeitung von Paris. Coislin. 187 - eingefügt.

**Comment by tklampfl** [comment]
Überprüft: funktioniert.
