### ISSUE TITLE
Vat. gr. 1422 (V5):  Ps 1-2 (full transcription): @copyOf nicht transfromierbar  

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#4]

**Comment by tklampfl** [comment]
In der Transformation Regel für ```quote``` erweitert, sodass ```copyOf``` des übergeordneten Segments übernommen wird. Z.B. ```vat-gr-1422-fr-1-10```:
![image](https://github.com/user-attachments/assets/5dd94e1e-28a9-451a-a470-a284367fb720)
