### ISSUE TITLE
Vat. gr. 754 (V1): HTML-Transkription: Liste der Quellen am Ende: Ab Ps 7 kann man nicht mehr zu den Fragmenten springen.  

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#5]
Kein dringendes issue:-)

**Comment by tklampfl** [comment]
Transformation für kritische Version erweitert - Sprungziel hat gefehlt.

**Comment by tklampfl** [comment]
Transformation für diplomatische Version erweitert - Sprungziel hat gefehlt.
