### ISSUE TITLE
Vat. gr. 754 (V1): <ref target="#coislin-10:coislin-10-fr-17-98" type="identical">(sub auctore Cyrillo)</ref>: nicht transformierbar

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#6]

**Comment by tklampfl** [comment]
Es haben die Verweise auf andere Handschriften generell gefehlt. Transformation um Regel für ```tei:ref``` erweitert (für die vereinfachte Präsentation).
![image](https://github.com/user-attachments/assets/b1294e1a-2c92-41bc-bc8a-6baf8ae0bebc)
