### ISSUE TITLE
Vat. gr. 1422 (V5): Ps 3-20 (List of contents): copyOf="#edition:edition-3-1-1" : nicht transformierbar

### ISSUE THREAD

**Issue by palamedes9** [acdh-oeaw/ExpPs#9]

**Comment by tklampfl** [comment]
Regel zur Transformation des Attributs ```copyOf``` hinzugefügt. Siehe z.B. Fragment ```vat-gr-1422-fr-17-206```:
![image](https://github.com/user-attachments/assets/49d3ffa4-39bc-42cb-bcd6-a8a91c9f8473)
